language: generic

cache:
  directories:
  - $HOME/local

env:
  global:
    - PATH=$HOME/local/bin:$HOME/local/evm/bin:$HOME/local/cask/bin:$PATH

# When there's a new major Emacs release, also update
# byte-compile-error-on-warn to the new release, below
matrix:
  include:
    - env: EVM_EMACS=emacs-25.1-travis
    - env: EVM_EMACS=emacs-25.3-travis
    - env: EVM_EMACS=emacs-26.1-travis
    - env: EVM_EMACS=emacs-git-snapshot-travis

before_install:
  - echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty/" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends --allow-unauthenticated
      r-recommended
      r-cran-roxygen2
      texinfo
      texlive-latex-base
      texlive-latex-recommended
      texlive-latex-extra

before_script:
  - sh targets/install-evm.sh
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - sh targets/install-cask.sh

  # link R executable to test defining runners based on other R
  # versions found on PATH. We're lying here that it is in fact a
  # different R version but that doesn't matter.
  - mkdir ess-r
  - ln -s $(which R) $PWD/ess-r/R-3.2.1
  - export PATH=$PATH:$PWD/ess-r/

script:
- emacs --version
- R --version
- cd lisp; make julia-mode.elc
- cd ..
- cp targets/travis-setup.el setup
- cp targets/travis-setup.el lisp/setup
- make -k all "EMACSBATCH = emacs -batch -Q -l setup"
- make test
